# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bookid', models.IntegerField()),
                ('review', models.CharField(max_length=750)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
